language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO="django==1.11.15"

matrix:
  include:
    - python: "3.4"
      env: DJANGO="django==2.0.8"
    - python: "3.5"
      env: DJANGO="django==2.0.8"
    - python: "3.6"
      env: DJANGO="django==2.0.8"
    - python: "3.5"
      env: DJANGO="django==2.1.0"
    - python: "3.6"
      env: DJANGO="django==2.1.0"

install:
  - pip install $DJANGO
  - pip install -e .
  - pip install flake8

before_script:
  - flake8 --ignore=E501,E225,E128,E126,E402,F401,F403 contact_form
  - cd contact_form/tests

script: python ./runtests.py
